# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plays',
            old_name='artistname',
            new_name='artistName',
        ),
        migrations.RenameField(
            model_name='plays',
            old_name='playid',
            new_name='playID',
        ),
        migrations.RenameField(
            model_name='plays',
            old_name='playtypeid',
            new_name='playtypeID',
        ),
        migrations.RenameField(
            model_name='plays',
            old_name='playtypename',
            new_name='playtypeName',
        ),
        migrations.RenameField(
            model_name='plays',
            old_name='releasename',
            new_name='releaseName',
        ),
        migrations.AlterField(
            model_name='plays',
            name='airdate',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='plays',
            name='releaseYear',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
