# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190525_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plays',
            name='airdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
